/**
 * 数据接口 
 * generated by ift @徐凯-鬼道
 *
 * @author 
 * @version 1.0.0
 * @date 5/20/13 5:22 PM
 */

/**
 * 兼容node和browser环境
 */
if (typeof exports === 'undefined') {
    exports = {};
}

exports.config = {
    "name": "这是接口名",
    "desc": "这是接口的详细描述",
    // 线上地址
    "url": "http://example.com/demo",
    // 日常地址
    "urlDaily": "http://daily.example.net/demo",
    // 预发地址
    "urlPrepub": "http://example.com/demo",
    // 支持的 Method 集合
    "method": ['GET', 'POST'],
    // 响应与模板的映射关系
    "template":{
        "response": "tpl1.php",
        "responseError": "tpl2.php"
    }
};

exports.request = {
    "id": "1000"   // 查询字段 
};

exports.response = {
    "success": true, // 标记成功
    "model": {
        // 规则：或者字段「title」不存在，若存在则「title」的值必须匹配正则表达式（不区分大小写，以 xyz 开头，数字结尾）
        // 详细规则请参考 http://work.tmall.net/projects/if/wiki/spec#响应
        "title__RULE__": "{{not-required}},{{/^xyz\\d+$/i}}",
        "title": "xyz0",
        // 规则：字段「list」允许不存在
        "list__RULE__": "{{not-required}}",
        "list": [// 列表数据
            {// 单条记录
                "id": 1000,
                "name": "name-123"
            },
            {// 单条记录
             "id": 1000,
             "name": "name-123"
            }
        ]
    }
};

exports.responseError = {
    "success": false, // 标记失败
    "model": {
        // 常见错误信息请参考  http://work.tmall.net/projects/if/wiki/suggest
        "error": "Error message"
    }
};
